const products = [
    { id: 1, name: 'Product 1', price: 29.99, original: 39.99, category: 'Electronics', rating: 4.5, reviews: 150, emoji: '📱', badge: 'New', tags: ['electronics', 'mobile'], desc: 'Latest smartphone with amazing features', seller: 'Seller A', isNew: true },
    { id: 2, name: 'Product 2', price: 49.99, original: 59.99, category: 'Home', rating: 4.0, reviews: 100, emoji: '🛋️', badge: 'Discount', tags: ['home', 'furniture'], desc: 'Comfortable sofa for your living room', seller: 'Seller B', isNew: false },
    { id: 3, name: 'Product 3', price: 19.99, original: 29.99, category: 'Beauty', rating: 4.8, reviews: 200, emoji: '💄', badge: 'Best Seller', tags: ['beauty', 'makeup'], desc: 'High-quality lipstick available in various colors', seller: 'Seller C', isNew: true },
    { id: 4, name: 'Product 4', price: 99.99, original: 129.99, category: 'Fashion', rating: 4.3, reviews: 50, emoji: '👗', badge: 'Trending', tags: ['fashion', 'clothing'], desc: 'Stylish dress for every occasion', seller: 'Seller D', isNew: false },
    { id: 5, name: 'Product 5', price: 59.99, original: 79.99, category: 'Health', rating: 4.7, reviews: 80, emoji: '🏋️', badge: 'New', tags: ['health', 'fitness'], desc: 'Fitness tracker to monitor your health', seller: 'Seller E', isNew: true },
    { id: 6, name: 'Product 6', price: 199.99, original: 249.99, category: 'Electronics', rating: 4.0, reviews: 40, emoji: '💻', badge: 'Discount', tags: ['electronics', 'laptop'], desc: 'High-performance laptop for professionals', seller: 'Seller F', isNew: false },
    { id: 7, name: 'Product 7', price: 15.99, original: 19.99, category: 'Beauty', rating: 4.5, reviews: 70, emoji: '🧴', badge: 'Best Seller', tags: ['beauty', 'skincare'], desc: 'Moisturizing lotion for daily use', seller: 'Seller G', isNew: true },
    { id: 8, name: 'Product 8', price: 299.99, original: 349.99, category: 'Electronics', rating: 4.6, reviews: 20, emoji: '📺', badge: 'New', tags: ['electronics', 'tv'], desc: 'Smart TV with 4K resolution', seller: 'Seller H', isNew: false },
    { id: 9, name: 'Product 9', price: 39.99, original: 49.99, category: 'Fashion', rating: 4.2, reviews: 65, emoji: '👖', badge: 'Trending', tags: ['fashion', 'clothing'], desc: 'Denim jeans for everyday wear', seller: 'Seller I', isNew: true },
    { id: 10, name: 'Product 10', price: 25.99, original: 30.00, category: 'Home', rating: 4.1, reviews: 90, emoji: '🏡', badge: 'New', tags: ['home', 'decor'], desc: 'Decorative items for your home', seller: 'Seller J', isNew: false },
    { id: 11, name: 'Product 11', price: 45.00, original: 60.00, category: 'Electronics', rating: 4.5, reviews: 120, emoji: '🎧', badge: 'Best Seller', tags: ['electronics', 'audio'], desc: 'Noise-cancelling headphones', seller: 'Seller K', isNew: true },
    { id: 12, name: 'Product 12', price: 75.99, original: 85.99, category: 'Health', rating: 4.3, reviews: 95, emoji: '💊', badge: 'Discount', tags: ['health', 'wellness'], desc: 'Multivitamins for daily health', seller: 'Seller L', isNew: false },
    { id: 13, name: 'Product 13', price: 89.99, original: 99.99, category: 'Beauty', rating: 4.9, reviews: 150, emoji: '💅', badge: 'Trending', tags: ['beauty', 'nails'], desc: 'Nail care set for perfect nails', seller: 'Seller M', isNew: true },
    { id: 14, name: 'Product 14', price: 59.99, original: 69.99, category: 'Fashion', rating: 4.4, reviews: 80, emoji: '👠', badge: 'Best Seller', tags: ['fashion', 'shoes'], desc: 'Elegant shoes for formal events', seller: 'Seller N', isNew: true },
    { id: 15, name: 'Product 15', price: 20.00, original: 25.00, category: 'Electronics', rating: 4.1, reviews: 45, emoji: '⌚', badge: 'New', tags: ['electronics', 'watch'], desc: 'Smartwatch for fitness enthusiasts', seller: 'Seller O', isNew: true },
    { id: 16, name: 'Product 16', price: 150.99, original: 199.99, category: 'Home', rating: 4.6, reviews: 130, emoji: '🛏️', badge: 'Discount', tags: ['home', 'furniture'], desc: 'Luxury bed for a comfortable sleep', seller: 'Seller P', isNew: false },
    { id: 17, name: 'Product 17', price: 305.99, original: 379.99, category: 'Electronics', rating: 4.8, reviews: 25, emoji: '🎮', badge: 'New', tags: ['electronics', 'gaming'], desc: 'Gaming console with the latest games', seller: 'Seller Q', isNew: true },
    { id: 18, name: 'Product 18', price: 8.99, original: 14.99, category: 'Beauty', rating: 4.0, reviews: 200, emoji: '🧖', badge: 'Best Seller', tags: ['beauty', 'spa'], desc: 'Relaxing face mask for deep hydration', seller: 'Seller R', isNew: true },
    { id: 19, name: 'Product 19', price: 30.50, original: 50.00, category: 'Fashion', rating: 4.7, reviews: 110, emoji: '🧥', badge: 'Trending', tags: ['fashion', 'outerwear'], desc: 'Winter coat to keep you warm', seller: 'Seller S', isNew: false },
    { id: 20, name: 'Product 20', price: 12.50, original: 15.00, category: 'Home', rating: 4.2, reviews: 90, emoji: '🔪', badge: 'New', tags: ['home', 'kitchen'], desc: 'Chef's knife for cooking enthusiasts', seller: 'Seller T', isNew: true },
    { id: 21, name: 'Product 21', price: 4.99, original: 5.99, category: 'Health', rating: 4.5, reviews: 150, emoji: '🌱', badge: 'Best Seller', tags: ['health', 'organic'], desc: 'Organic green tea for a healthy lifestyle', seller: 'Seller U', isNew: false },
    { id: 22, name: 'Product 22', price: 18.99, original: 24.99, category: 'Beauty', rating: 4.6, reviews: 120, emoji: '🧖‍♀️', badge: 'Discount', tags: ['beauty', 'skincare'], desc: 'Refreshing facial mist for hydration', seller: 'Seller V', isNew: true },
    { id: 23, name: 'Product 23', price: 11.99, original: 15.99, category: 'Fashion', rating: 4.3, reviews: 80, emoji: '👜', badge: 'New', tags: ['fashion', 'accessories'], desc: 'Stylish handbag for all occasions', seller: 'Seller W', isNew: false },
    { id: 24, name: 'Product 24', price: 7.99, original: 10.99, category: 'Home', rating: 4.4, reviews: 60, emoji: '🏠', badge: 'Best Seller', tags: ['home', 'decor'], desc: 'Cute decorative item for your home', seller: 'Seller X', isNew: true }
];

export default products;